name: arabic_handwriting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - opencv
  - pyyaml
  - click
  - pillow
  - tqdm
  - pip
  - pip:
    - protobuf
    - tensorboard
    - sympy
    - omegaconf